fix - 버그 수정
1.IdentifierGenerationException: ids for this class must be manually assigned before calling save()

2.SQLException: Field 'board_id' doesn't have a default value

오류 수정
-> @GeneratedValue 미설정